from github_code_crawler.code_processing import RejectedCode, process_code
from github_code_crawler.config import FileFilterConfig, QualityConfig


FILE_CONFIG = FileFilterConfig(
    extensions=(".py",),
    max_file_size_bytes=1_000_000,
    min_code_characters=20,
    min_code_lines=2,
    min_tokens=5,
    max_code_characters=50_000,
    ignore_directories=frozenset(),
)

QUALITY_CONFIG = QualityConfig(
    syntax_check=True,
    reject_generated_code=True,
    generated_markers=("generated by", "do not edit"),
    reject_binary=True,
    max_repeated_line_ratio=0.80,
)


def test_code_is_cleaned_and_validated():
    result = process_code("def add(a, b):   \r\n    return a + b\r\n", FILE_CONFIG, QUALITY_CONFIG)
    assert result.code == "def add(a, b):\n    return a + b"
    assert result.exact_hash
    assert result.structural_hash


def test_syntax_error_is_rejected():
    try:
        process_code("def broken(:\n    pass\n", FILE_CONFIG, QUALITY_CONFIG)
    except RejectedCode as exc:
        assert exc.reason.startswith("syntax_error")
    else:
        raise AssertionError("syntax error was not rejected")


def test_generated_code_is_rejected():
    try:
        process_code(
            "# This file was generated by a tool\ndef f():\n    return 1\n",
            FILE_CONFIG,
            QUALITY_CONFIG,
        )
    except RejectedCode as exc:
        assert exc.reason == "generated_code"
    else:
        raise AssertionError("generated code was not rejected")
